/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_supsi_dti_backend_license_LicenseChecker */

#ifndef _Included_ch_supsi_dti_backend_license_LicenseChecker
#define _Included_ch_supsi_dti_backend_license_LicenseChecker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_supsi_dti_backend_license_LicenseChecker
 * Method:    checkLicense
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ch_supsi_dti_backend_license_LicenseChecker_checkLicense
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
